import { Database, Loader2, X } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";

import type { MatchSummary, TxlineProbeKind, TxlineProbeResult } from "../../runtime/api";

type Props = { open: boolean; selectedMatch: MatchSummary | null; probeKind: TxlineProbeKind; probeState: "idle" | "loading" | "ready" | "error"; probe: TxlineProbeResult | null; onClose: () => void; onRunProbe: (kind: TxlineProbeKind) => void };

function summary(payload: unknown) {
  if (Array.isArray(payload)) return `${payload.length} registros`;
  if (payload && typeof payload === "object") { const keys = Object.keys(payload as Record<string, unknown>).slice(0, 8); return keys.length ? keys.join(" · ") : "Objeto vazio"; }
  return payload == null ? "Resposta vazia" : String(payload).slice(0, 140);
}

export function TxlineTechnicalInspector({ open, selectedMatch, probeKind, probeState, probe, onClose, onRunProbe }: Props) {
  return <AnimatePresence>{open ? <motion.div className="fixed inset-0 z-[108] bg-[#050814]/80 backdrop-blur-md" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && onClose()}><motion.aside role="dialog" aria-modal="true" aria-label="Inspeção técnica TxLINE" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", stiffness: 320, damping: 34 }} className="ml-auto flex h-dvh w-full max-w-[680px] flex-col border-l border-white/12 bg-[#080d19]"><header className="flex items-center justify-between border-b border-white/12 px-5 py-5"><div><p className="font-['DM_Mono'] text-[9px] uppercase tracking-[.16em] text-primary">Inspeção técnica TxLINE</p><h2 className="mt-2 font-['Chakra_Petch'] text-2xl font-black uppercase">Fixture {selectedMatch?.fixtureId ?? "--"}</h2></div><button type="button" onClick={onClose} aria-label="Fechar inspeção" className="grid size-10 place-items-center border border-white/12 text-white/50 hover:text-white"><X className="size-4" /></button></header><div className="flex-1 overflow-y-auto p-5"><p className="max-w-lg text-sm leading-6 text-white/45">Ferramenta de demonstração para validar os endpoints reais usados pela Home. Ela não altera a partida nem cria dados substitutos.</p><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">{(["scores", "updates", "historical", "odds"] as TxlineProbeKind[]).map((kind) => <button key={kind} type="button" onClick={() => onRunProbe(kind)} disabled={!selectedMatch || probeState === "loading"} className={`min-h-11 border px-3 font-['DM_Mono'] text-[9px] uppercase ${probeKind === kind && probe ? "border-primary bg-primary/10 text-primary" : "border-white/12 text-white/45 hover:border-primary/40"}`}>{kind}</button>)}</div><section className="mt-5 border-y border-white/12 py-5"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 font-['DM_Mono'] text-[9px] uppercase text-white/35">{probeState === "loading" ? <Loader2 className="size-4 animate-spin text-primary" /> : <Database className="size-4" />}Estado do request</span><strong className={probe?.ok ? "text-primary" : probeState === "error" ? "text-red-400" : "text-white/40"}>{probeState === "idle" ? "Não solicitado" : probe ? `HTTP ${probe.status}` : "Erro"}</strong></div><p className="mt-5 break-all font-['DM_Mono'] text-xs text-white/45">{probe?.endpoint ?? "Selecione um endpoint."}</p><p className="mt-4 text-sm leading-6">{probe ? summary(probe.payload) : "Aguardando inspeção."}</p></section></div></motion.aside></motion.div> : null}</AnimatePresence>;
}
