import { ArrowLeft, ArrowRight, Check, Clock3, LockKeyhole, Share2, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router";
import { useLocale } from "../../i18n/locale-context";
import { ShareSheet } from "../../social/ShareSheet";
import type { ShareResponse } from "../../social/share";
import { ViraLoader } from "../../shared/brand/ViraLoader";
import { AppShell } from "../../shared/shell/AppShell";
import { confirmPicks, ensurePicksIdentity, fetchOwnerPicks, fetchPicksCatalog, fetchPublicPicks, sharePicks, trackPicksOpen } from "./api";
import type { ViraPicksCardV1, ViraPicksCatalogV1 } from "./contracts";

const copy = {
  en: { title: "Make your match picks. Share with friends.", disclosure: "Social predictions. No money involved.", back: "Match Preview", result: "Regular-time result", goals: "Total regular-time goals", btts: "Both teams score", home: "Home", draw: "Draw", away: "Away", over: "Over 2.5", under: "Under 2.5", yes: "Yes", no: "No", consensus: "Market consensus", unavailable: "Consensus unavailable", refreshingMarket: "Refreshing the TxLINE consensus.", staleMarket: "The last market observation is too old to use.", invalidMarket: "This market is not currently available for VIRA Picks.", count: (n: number, total = 2) => `${n} of ${total}`, name: "Your name", confirmRule: "I understand this card cannot be changed after confirmation.", confirm: "Confirm immutable card", confirming: "Confirming card", locked: "Immutable card", locks: "Locks at kickoff", share: "Share", editDenied: "Confirmed picks cannot be edited.", makeOwn: "Make your picks", loading: "Synchronizing VIRA Picks", unavailableTitle: "Picks unavailable", unavailableBody: "The required TxLINE market authority is not available for this fixture.", error: "VIRA Picks could not complete that action.", pending: "Pending", correct: "Correct", missed: "Missed", void: "Void", room: "Match Room", perfect: "Perfect read", two: "Two correct", one: "One correct", zero: "No hits this time", allVoid: "Match unavailable" },
  "pt-BR": { title: "Faça suas previsões para a partida e compartilhe com amigos.", disclosure: "Previsões sociais. Sem dinheiro envolvido.", back: "Prévia da partida", result: "Resultado no tempo regulamentar", goals: "Total de gols no tempo regulamentar", btts: "Ambas as equipes marcam", home: "Casa", draw: "Empate", away: "Visitante", over: "Mais de 2,5", under: "Menos de 2,5", yes: "Sim", no: "Não", consensus: "Consenso de mercado", unavailable: "Consenso indisponível", refreshingMarket: "Atualizando o consenso TxLINE.", staleMarket: "A última observação do mercado é antiga demais para uso.", invalidMarket: "Este mercado não está disponível no VIRA Picks agora.", count: (n: number, total = 2) => `${n} de ${total}`, name: "Seu nome", confirmRule: "Entendo que este card não poderá ser alterado após a confirmação.", confirm: "Confirmar card imutável", confirming: "Confirmando card", locked: "Card imutável", locks: "Fecha no início da partida", share: "Compartilhar", editDenied: "Previsões confirmadas não podem ser editadas.", makeOwn: "Faça suas previsões", loading: "Sincronizando VIRA Picks", unavailableTitle: "Picks indisponível", unavailableBody: "A autoridade necessária dos mercados TxLINE não está disponível para esta partida.", error: "O VIRA Picks não conseguiu concluir esta ação.", pending: "Pendente", correct: "Correta", missed: "Incorreta", void: "Anulada", room: "Match Room", perfect: "Leitura perfeita", two: "Duas corretas", one: "Uma correta", zero: "Nenhum acerto desta vez", allVoid: "Partida indisponível" },
} as const;

const labels: Record<string, keyof typeof copy.en> = { "match_result:home": "home", "match_result:draw": "draw", "match_result:away": "away", "total_goals:2.5:over": "over", "total_goals:2.5:under": "under", "both_teams_score:yes": "yes", "both_teams_score:no": "no" };
const kindLabels: Record<string, keyof typeof copy.en> = { match_result: "result", total_goals: "goals", both_teams_score: "btts" };
const selectionId = (selection: ViraPicksCardV1["selections"][number]) => selection.kind === "total_goals" ? `${selection.kind}:2.5:${selection.selection}` : `${selection.kind}:${selection.selection}`;

function marketUnavailableCopy(reason: string | undefined, strings: typeof copy.en | typeof copy["pt-BR"]) {
  if (["market_acquisition_stale", "market_endpoint_unavailable", "market_authority_insufficient", "market_freshness_unknown"].includes(reason ?? "")) return strings.refreshingMarket;
  if (reason === "market_stale") return strings.staleMarket;
  return strings.invalidMarket;
}

function ResultSummary({ card, strings }: { card: ViraPicksCardV1; strings: typeof copy.en | typeof copy["pt-BR"] }) {
  const results = card.results ?? []; const correct = results.filter((item) => item.status === "correct").length; const allVoid = results.length > 0 && results.every((item) => item.status === "void");
  if (card.status !== "resolved" && card.status !== "void") return null;
  const summary = correct === results.length ? `${correct}/${results.length} — ${strings.perfect}` : correct === 2 ? `${correct}/${results.length} — ${strings.two}` : correct === 1 ? `${correct}/${results.length} — ${strings.one}` : `0/${results.length} — ${strings.zero}`;
  return <p className="mt-5 font-['Chakra_Petch'] text-3xl font-black uppercase text-primary">{allVoid ? strings.allVoid : summary}</p>;
}

export function ViraPicksScreen() {
  const { fixtureId = "" } = useParams(); const [params] = useSearchParams(); const sharedCode = params.get("card");
  const { locale, timeZone, localizedHref, formatDateTime, formatPercent, teamName } = useLocale(); const strings = copy[locale];
  const [catalog, setCatalog] = useState<ViraPicksCatalogV1 | null>(null); const [card, setCard] = useState<ViraPicksCardV1 | null>(null); const [sharedCard, setSharedCard] = useState<ViraPicksCardV1 | null>(null);
  const [selected, setSelected] = useState<Record<string, string>>({}); const [displayName, setDisplayName] = useState(() => localStorage.getItem("vira:displayName") ?? ""); const [accepted, setAccepted] = useState(false); const [state, setState] = useState<"loading" | "ready" | "confirming" | "error">("loading"); const [share, setShare] = useState<ShareResponse | null>(null); const [editDenied, setEditDenied] = useState(false); const errorRef = useRef<HTMLParagraphElement>(null);
  useEffect(() => { let active = true; setState("loading"); Promise.all([fetchPicksCatalog(fixtureId, locale), fetchOwnerPicks(fixtureId, locale).catch(() => ({ card: null }))]).then(([nextCatalog, owner]) => { if (!active) return; setCatalog(nextCatalog); setCard(owner.card); setState("ready"); }).catch(() => active && setState("error")); return () => { active = false; }; }, [fixtureId, locale]);
  useEffect(() => { if (!sharedCode) return; fetchPublicPicks(sharedCode, locale).then((response) => setSharedCard(response.card)).catch(() => undefined); void trackPicksOpen(sharedCode, locale); }, [sharedCode, locale]);
  useEffect(() => { if (state === "error") errorRef.current?.focus(); }, [state]);
  const count = Object.keys(selected).length; const fixture = catalog?.fixture; const available = catalog?.questions.some((question) => question.available) ?? false;
  const kickoff = fixture?.kickoffAt ? formatDateTime(fixture.kickoffAt, { timeZone, day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "—";
  const confirm = async () => { if (!fixture || count < 1 || count > 3 || !accepted || !displayName.trim()) return; setState("confirming"); try { localStorage.setItem("vira:displayName", displayName.trim()); await ensurePicksIdentity(displayName.trim(), locale); if (sharedCode) await trackPicksOpen(sharedCode, locale); const response = await confirmPicks(fixture.fixtureId, Object.values(selected), crypto.randomUUID(), locale); setCard(response.card); setState("ready"); requestAnimationFrame(() => document.querySelector<HTMLElement>("[data-picks-card]")?.focus()); } catch { setState("error"); } };
  const openShare = async (target: ViraPicksCardV1) => { try { setShare(await sharePicks(target.id, locale)); } catch { setState("error"); } };
  const visibleCard = card ?? sharedCard; const ownConfirmed = Boolean(card);
  if (state === "loading") return <AppShell><main className="grid min-h-[70vh] place-items-center"><ViraLoader label={strings.loading} /></main></AppShell>;
  if (!catalog?.enabled) return <AppShell><main className="mx-auto max-w-3xl px-6 py-20"><h1 className="font-['Chakra_Petch'] text-5xl font-black uppercase">{strings.unavailableTitle}</h1><p className="mt-5 text-white/50">{strings.unavailableBody}</p></main></AppShell>;
  return <AppShell><main className="min-h-screen bg-[#070a13]/60 pb-52 text-white md:pb-16">
    <header className="border-b border-white/15 bg-[url('/textures/vira-carbon.webp')] bg-[length:640px_640px]"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><Link to={localizedHref(`/match/${fixtureId}/preview`)} className="inline-flex items-center gap-2 text-xs uppercase text-white/50 hover:text-primary"><ArrowLeft className="size-4" />{strings.back}</Link><p className="mt-10 font-['DM_Mono'] text-[10px] font-black uppercase tracking-[.2em] text-primary">VIRA Picks</p><h1 className="mt-4 max-w-4xl font-['Chakra_Petch'] text-[clamp(2.6rem,7vw,6rem)] font-black uppercase leading-[.86]">{strings.title}</h1><p className="mt-5 text-sm text-white/55">{strings.disclosure}</p><div className="mt-8 flex flex-wrap gap-5 border-t border-white/15 pt-5 font-['DM_Mono'] text-[10px] uppercase text-white/50"><span>{teamName(fixture?.homeTeam ?? "")} × {teamName(fixture?.awayTeam ?? "")}</span><span className="text-primary">{kickoff}</span></div></div></header>
    <div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[minmax(0,1fr)_320px]">
      <section data-vira-picks-builder aria-label="VIRA Picks builder" className="min-w-0">
        {sharedCard && !card ? <article className="mb-10 border border-primary/35 bg-primary/[.05] p-6"><p className="font-['DM_Mono'] text-[10px] uppercase text-primary">{sharedCard.displayName} · VIRA Picks</p><CardRows card={sharedCard} strings={strings} /><ResultSummary card={sharedCard} strings={strings} /></article> : null}
        {ownConfirmed ? <article data-picks-card tabIndex={-1} className="border border-primary/40 bg-[#0b1320] p-6 outline-none focus:border-primary"><div className="flex items-center justify-between gap-4"><div><p className="font-['DM_Mono'] text-[10px] uppercase text-primary">{strings.locked}</p><h2 className="mt-2 font-['Chakra_Petch'] text-3xl font-black uppercase">{card.displayName}</h2></div><LockKeyhole className="size-6 text-primary" /></div><CardRows card={card} strings={strings} /><ResultSummary card={card} strings={strings} /><p className="mt-6 flex items-center gap-2 text-xs text-white/45"><Clock3 className="size-4" />{strings.locks} · {kickoff}</p><div className="mt-6 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => void openShare(card)} className="flex min-h-14 items-center justify-center gap-2 bg-primary font-black uppercase text-[#070a13]"><Share2 className="size-4" />{strings.share}</button><button type="button" onClick={() => setEditDenied(true)} className="min-h-14 border border-white/20 font-black uppercase text-white/60">{strings.confirm}</button></div>{editDenied ? <p role="alert" className="mt-3 text-sm text-amber-200">{strings.editDenied}</p> : null}</article> : <div className="space-y-8">{catalog.questions.map((question) => <fieldset key={question.kind} disabled={!question.available}><legend className="font-['Chakra_Petch'] text-2xl font-black uppercase">{strings[kindLabels[question.kind]] as string}</legend><p className="mt-2 text-xs text-white/40">{question.available && question.observedAt ? `${strings.consensus} · ${formatDateTime(question.observedAt, { timeZone, hour: "2-digit", minute: "2-digit" })}` : `${strings.unavailable} · ${marketUnavailableCopy(question.unavailableReason, strings)}`}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{question.options.map((option) => <button key={option.id} type="button" aria-pressed={selected[question.kind] === option.id} onClick={() => setSelected((current) => ({ ...current, [question.kind]: option.id }))} className={`min-h-16 border px-4 text-left disabled:opacity-35 ${selected[question.kind] === option.id ? "border-primary bg-primary text-[#070a13]" : "border-white/20 bg-white/[.025] hover:border-primary"}`}><span className="block font-black uppercase">{strings[labels[option.id]] as string}</span><span className="mt-1 block font-['DM_Mono'] text-[10px] opacity-60">{option.consensus !== undefined ? `${strings.consensus}: ${formatPercent(option.consensus, { maximumFractionDigits: 0 })}` : strings.unavailable}</span></button>)}</div></fieldset>)}</div>}
        {!ownConfirmed ? <div className="mt-10 border-t border-white/15 pt-8"><label className="block text-xs font-bold uppercase text-white/55" htmlFor="picks-name">{strings.name}</label><input id="picks-name" value={displayName} maxLength={40} onChange={(event) => setDisplayName(event.target.value)} className="mt-2 min-h-13 w-full border border-white/20 bg-transparent px-4 outline-none focus:border-primary" /><label className="mt-5 flex items-start gap-3 text-sm text-white/60"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} className="mt-1 size-4 accent-[#c8ff00]" /><span>{strings.confirmRule}</span></label><button type="button" disabled={!available || count < 1 || !accepted || !displayName.trim() || state === "confirming"} onClick={() => void confirm()} className="mt-6 flex min-h-16 w-full items-center justify-between bg-primary px-6 font-['Chakra_Petch'] font-black uppercase text-[#070a13] disabled:opacity-35"><span>{state === "confirming" ? strings.confirming : strings.confirm}</span><ArrowRight className="size-5" /></button></div> : null}
        {state === "error" ? <p ref={errorRef} tabIndex={-1} role="alert" className="mt-5 text-sm text-red-300">{strings.error}</p> : null}
      </section>
      <aside className="h-fit border border-white/15 bg-[#0b1320] p-6 lg:sticky lg:top-24"><div className="flex items-center justify-between"><span className="font-['DM_Mono'] text-xs font-black text-primary">{strings.count(count || card?.selections.length || 0)}</span><ShieldCheck className="size-5 text-primary" /></div><div className="mt-5 space-y-3">{Object.values(selected).map((id) => <p key={id} className="border-b border-white/10 pb-3 text-sm font-bold uppercase">{strings[labels[id]] as string}</p>)}</div><p className="mt-6 text-xs leading-5 text-white/40">{strings.disclosure}</p><div className="mt-6 grid gap-2"><Link to={localizedHref(`/match/${fixtureId}/preview`)} className="flex min-h-12 items-center justify-between border border-white/20 px-4 text-xs font-black uppercase">{strings.back}<ArrowRight className="size-4" /></Link><Link to={localizedHref(`/match/${fixtureId}`)} className="flex min-h-12 items-center justify-between border border-white/20 px-4 text-xs font-black uppercase">{strings.room}<ArrowRight className="size-4" /></Link></div></aside>
    </div>
    {!ownConfirmed ? <div className="fixed inset-x-0 bottom-[var(--shell-mobile-dock-height)] z-[41] border-t border-white/15 bg-[#070a13]/95 p-3 backdrop-blur lg:hidden"><button type="button" disabled={count < 1 || !accepted || !displayName.trim()} onClick={() => void confirm()} className="flex min-h-14 w-full items-center justify-between bg-primary px-5 font-black uppercase text-[#070a13] disabled:opacity-35"><span>{strings.count(count)} · {strings.confirm}</span><Check className="size-4" /></button></div> : null}
    <ShareSheet share={share} onClose={() => setShare(null)} />
  </main></AppShell>;
}

function CardRows({ card, strings }: { card: ViraPicksCardV1; strings: typeof copy.en | typeof copy["pt-BR"] }) {
  return <div className="mt-6 divide-y divide-white/10 border-y border-white/10">{card.selections.length ? card.selections.map((selection, index) => { const result = card.results?.[index]; return <div key={selection.kind} className="flex items-center justify-between gap-5 py-4"><div><p className="text-[10px] uppercase text-white/35">{strings[kindLabels[selection.kind]] as string}</p><p className="mt-1 font-black uppercase">{strings[labels[selectionId(selection)]] as string}</p></div><span className={`font-['DM_Mono'] text-[10px] font-black uppercase ${result?.status === "correct" ? "text-primary" : result?.status === "missed" ? "text-red-300" : "text-white/40"}`}>{strings[result?.status ?? "pending"] as string}</span></div>; }) : <p className="py-5 text-sm text-white/45">{strings.locks}</p>}</div>;
}
