import { ArrowRight, Check, Clock3, ExternalLink, Film, GitBranch, LockKeyhole, Radio, RefreshCw, ShieldCheck, Sparkles, Trophy, Users } from "lucide-react";
import { useEffect, useState, type ComponentType } from "react";
import { Link } from "react-router";
import { deriveReviewConclusions } from "../../app/shell/review-summary.ts";
import { useShellAtmosphere } from "../../app/shell/use-shell-atmosphere.ts";
import { useLocale } from "../../i18n/locale-context.tsx";
import { replayQuestion, replayResolutionLabel } from "../../i18n/replay-copy.ts";
import { stableOptionLabel } from "../../i18n/round-copy.ts";
import { fetchPublicPlayback } from "../../runtime/api.ts";
import { ViraLoader } from "../../shared/brand/ViraLoader.tsx";

type Playback = Awaited<ReturnType<typeof fetchPublicPlayback>>;
type Icon = ComponentType<{ className?: string }>;

const DEMO_URL = "https://www.youtube.com/watch?v=LnOd2kWTiGA";
const REPO_URL = "https://github.com/4LFR3Dv1/VIRA-";
const PITCH_URL = "https://github.com/4LFR3Dv1/VIRA-/blob/main/docs/VIRA_Synchronized_Football_Engagement.pdf";

const copy = {
  en: {
    kicker: "Judge evaluation guide · no login",
    title: "Evaluate the complete VIRA journey.",
    description: "Three paths show what fans do before kickoff, during the match and when no fixture is live. Start with the live product, then inspect the certified evidence.",
    openProduct: "Open live product", watchDemo: "Watch demo", resources: "Submission resources", repository: "Public repository", pitch: "Commercial pitch",
    fastPath: "Three-minute fast path", fastPathDescription: "Choose the path available at the time of review. The certified playback is always available.",
    before: "01 · Available before kickoff", picks: "VIRA Picks", picksDescription: "Choose a scheduled fixture, confirm an immutable social prediction card and share it with a second guest.", picksSteps: ["1–3 structured picks", "Locks at kickoff", "Separate from Match Room ranking"], picksCta: "Choose a scheduled match",
    live: "02 · During a live fixture", room: "Match Room", roomDescription: "Join with two guest identities, answer the same short challenge and watch the server lock and resolve it for everyone.", roomSteps: ["Private answers until lock", "TxLINE-driven resolution", "Synchronized points and ranking"], roomCta: "Find a live match",
    anytime: "03 · Available anytime", playback: "Certified playback", playbackDescription: "Run a guided TxLINE fixture reconstructed from the append-only ledger by the production runtime.", playbackSteps: ["10-second guided start", "Projection and ranking replay", "Public hash-chain proof"], playbackCta: "Inspect the evidence",
    reassurance: ["No wallet or account", "No money involved", "EN and PT-BR", "Desktop and mobile"],
    evidenceKicker: "Certified evidence · available anytime", evidenceTitle: "From TxLINE observation to reproducible result.", capturedDisclosure: "This is a sanitized deterministic TxLINE test fixture persisted in the append-only ledger and replayed by the production runtime. It is not presented as current live delivery.",
    chainTitle: "TxLINE authority chain", input: "1 · Provider observation", inputDescription: "Exact market context and provider sequence enter the server-owned rule.", lock: "2 · Immutable server lock", lockDescription: "Only answers admitted before the absolute deadline can score.", rule: "3 · Deterministic rule", ruleDescription: "Structured values evaluate the frozen predicate; labels do not command the result.", output: "4 · Reproducible output", outputDescription: "Scoring, projection and ranking are rebuilt from the same ledger events.",
    market: "Market", sequence: "Provider sequence", observed: "Observed", answers: "Answers admitted", lockedAt: "Locked", expression: "Expression", winner: "Winning option", points: "Points applied", unavailableEvidence: "Certified playback temporarily unavailable", unavailableDescription: "The evaluation guide remains available. Retry the evidence or continue to the live match catalog.", retry: "Retry evidence", openMatches: "Open matches", proofTitle: "Independent replay checks", technical: "Technical evidence", fixtureType: "Fixture type", acquisition: "Acquisition origin", round: "Round", replayHash: "Replay hash", eventRange: "Event range hash", stream: "Stream range", openMatch: "Start guided playback", productLinks: "Continue the evaluation",
  },
  "pt-BR": {
    kicker: "Guia de avaliação · sem login",
    title: "Avalie a jornada completa do VIRA.",
    description: "Três caminhos mostram o que o fã faz antes do início, durante o jogo e quando não há partida ao vivo. Comece pelo produto e depois inspecione a evidência certificada.",
    openProduct: "Abrir produto", watchDemo: "Ver demo", resources: "Recursos da submissão", repository: "Repositório público", pitch: "Pitch comercial",
    fastPath: "Caminho rápido de três minutos", fastPathDescription: "Escolha o caminho disponível no momento da avaliação. O playback certificado está sempre disponível.",
    before: "01 · Disponível antes do início", picks: "VIRA Picks", picksDescription: "Escolha uma partida agendada, confirme um card social imutável e compartilhe com um segundo convidado.", picksSteps: ["1–3 previsões estruturadas", "Fecha no início da partida", "Separado do ranking da Match Room"], picksCta: "Escolher partida agendada",
    live: "02 · Durante uma partida ao vivo", room: "Match Room", roomDescription: "Entre com duas identidades convidadas, responda ao mesmo desafio e veja o servidor travar e resolver para todos.", roomSteps: ["Respostas privadas até o lock", "Resolução orientada pela TxLINE", "Pontos e ranking sincronizados"], roomCta: "Encontrar partida ao vivo",
    anytime: "03 · Disponível a qualquer momento", playback: "Playback certificado", playbackDescription: "Execute uma fixture TxLINE guiada, reconstruída do ledger append-only pelo runtime de produção.", playbackSteps: ["Início guiado em 10 segundos", "Replay de projeção e ranking", "Prova pública da cadeia de hashes"], playbackCta: "Inspecionar evidência",
    reassurance: ["Sem wallet ou conta", "Sem dinheiro envolvido", "EN e PT-BR", "Desktop e mobile"],
    evidenceKicker: "Evidência certificada · sempre disponível", evidenceTitle: "Da observação TxLINE ao resultado reproduzível.", capturedDisclosure: "Esta é uma fixture de teste TxLINE sanitizada e determinística, persistida no ledger append-only e reproduzida pelo runtime de produção. Ela não é apresentada como entrega ao vivo no momento da avaliação.",
    chainTitle: "Cadeia de autoridade TxLINE", input: "1 · Observação do provider", inputDescription: "O contexto exato do mercado e a sequência do provider entram na regra controlada pelo servidor.", lock: "2 · Lock imutável do servidor", lockDescription: "Somente respostas admitidas antes do prazo absoluto podem pontuar.", rule: "3 · Regra determinística", ruleDescription: "Valores estruturados avaliam o predicado congelado; textos não comandam o resultado.", output: "4 · Saída reproduzível", outputDescription: "Pontuação, projeção e ranking são reconstruídos dos mesmos eventos do ledger.",
    market: "Mercado", sequence: "Sequência do provider", observed: "Observado", answers: "Respostas admitidas", lockedAt: "Travado", expression: "Expressão", winner: "Opção vencedora", points: "Pontos aplicados", unavailableEvidence: "Playback certificado temporariamente indisponível", unavailableDescription: "O guia de avaliação continua disponível. Tente novamente ou prossiga para o catálogo de partidas.", retry: "Tentar evidência", openMatches: "Abrir partidas", proofTitle: "Verificações independentes do replay", technical: "Evidência técnica", fixtureType: "Tipo de fixture", acquisition: "Origem da aquisição", round: "Rodada", replayHash: "Hash do replay", eventRange: "Hash do intervalo", stream: "Intervalo do stream", openMatch: "Iniciar playback guiado", productLinks: "Continuar avaliação",
  },
} as const;

export function HelpScreen() {
  const { locale, localizedHref } = useLocale();
  const strings = copy[locale];
  const [data, setData] = useState<Playback | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useShellAtmosphere("route:help", { atmosphere: "finished", context: "post-match", fixtureFocus: .18, priority: 20 });
  const load = () => { setState("loading"); void fetchPublicPlayback().then((value) => { setData(value); setState("ready"); }).catch(() => setState("error")); };
  useEffect(load, []);

  return <main className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-12 lg:py-14">
    <header className="border-b border-white/15 pb-10 lg:pb-14">
      <p className="font-['DM_Mono'] text-[10px] font-black uppercase tracking-[.18em] text-primary">{strings.kicker}</p>
      <div className="mt-5 grid gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><h1 className="max-w-5xl font-['Chakra_Petch'] text-[clamp(3rem,8vw,7.8rem)] font-black uppercase leading-[.82]">{strings.title}</h1><p className="mt-7 max-w-3xl text-sm leading-6 text-white/55">{strings.description}</p></div><div className="grid gap-2"><Link to={localizedHref("/matches")} className="flex min-h-14 items-center justify-between bg-primary px-5 text-xs font-black uppercase text-[#050814]">{strings.openProduct}<ArrowRight className="size-4" /></Link><ExternalButton href={DEMO_URL} label={strings.watchDemo} icon={Film} /></div></div>
      <nav aria-label={strings.resources} className="mt-8 flex flex-wrap gap-x-6 gap-y-3 border-t border-white/10 pt-5"><span className="font-['DM_Mono'] text-[9px] uppercase text-white/30">{strings.resources}</span><ExternalTextLink href={REPO_URL} label={strings.repository} /><ExternalTextLink href={PITCH_URL} label={strings.pitch} /></nav>
    </header>

    <section className="py-12 lg:py-16" aria-labelledby="judge-fast-path"><div className="max-w-3xl"><p className="font-['DM_Mono'] text-[10px] uppercase text-primary">VIRA · 01—03</p><h2 id="judge-fast-path" className="mt-3 font-['Chakra_Petch'] text-4xl font-black uppercase sm:text-6xl">{strings.fastPath}</h2><p className="mt-4 text-sm text-white/50">{strings.fastPathDescription}</p></div><div className="mt-9 grid gap-px bg-white/15 lg:grid-cols-3"><PathCard eyebrow={strings.before} title={strings.picks} description={strings.picksDescription} steps={strings.picksSteps} cta={strings.picksCta} href={localizedHref("/matches")} icon={Sparkles} /><PathCard eyebrow={strings.live} title={strings.room} description={strings.roomDescription} steps={strings.roomSteps} cta={strings.roomCta} href={localizedHref("/matches")} icon={Users} /><PathCard eyebrow={strings.anytime} title={strings.playback} description={strings.playbackDescription} steps={strings.playbackSteps} cta={strings.playbackCta} href="#verified-playback" icon={ShieldCheck} /></div><div className="grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{strings.reassurance.map((item) => <p key={item} className="flex items-center gap-3 bg-[#070b15] px-5 py-4 font-['DM_Mono'] text-[9px] uppercase text-white/45"><Check className="size-3 text-primary" />{item}</p>)}</div></section>

    <PlaybackSection state={state} data={data} onRetry={load} />

    <footer className="mt-12 grid gap-px bg-white/15 sm:grid-cols-3"><Link to={localizedHref("/")} className="flex min-h-16 items-center justify-between bg-[#070b15] px-5 text-xs font-black uppercase hover:text-primary">{strings.openProduct}<ArrowRight className="size-4" /></Link><ExternalButton href={DEMO_URL} label={strings.watchDemo} icon={Film} /><ExternalButton href={REPO_URL} label={strings.repository} icon={GitBranch} /></footer>
  </main>;
}

function PlaybackSection({ state, data, onRetry }: { state: "loading" | "ready" | "error"; data: Playback | null; onRetry: () => void }) {
  const { formatDateTime, formatPercent, locale, localizedHref, t } = useLocale();
  const strings = copy[locale];
  const available = state === "ready" && data?.available && data.replay && data.verification && data.room;
  return <section id="verified-playback" className="scroll-mt-24 border-t border-white/15 pt-12 lg:pt-16" aria-labelledby="playback-title"><p className="font-['DM_Mono'] text-[10px] uppercase text-primary">{strings.evidenceKicker}</p><h2 id="playback-title" className="mt-4 max-w-5xl font-['Chakra_Petch'] text-[clamp(2.8rem,7vw,6.5rem)] font-black uppercase leading-[.86]">{strings.evidenceTitle}</h2><p className="mt-6 max-w-4xl border-l-2 border-primary pl-5 text-sm leading-6 text-white/55">{strings.capturedDisclosure}</p>
    {state === "loading" ? <div className="mt-10 grid min-h-64 place-items-center border border-white/10"><ViraLoader label={t("playback.loading")} /></div> : null}
    {!available && state !== "loading" ? <div className="mt-10 border border-white/15 p-7 sm:p-10"><h3 className="font-['Chakra_Petch'] text-3xl font-black uppercase">{strings.unavailableEvidence}</h3><p className="mt-4 max-w-2xl text-sm text-white/50">{strings.unavailableDescription}</p><div className="mt-7 flex flex-wrap gap-2"><button type="button" onClick={onRetry} className="inline-flex min-h-12 items-center gap-2 border border-white/20 px-5 text-xs font-black uppercase"><RefreshCw className="size-4" />{strings.retry}</button><Link to={localizedHref("/matches")} className="inline-flex min-h-12 items-center bg-primary px-5 text-xs font-black uppercase text-[#050814]">{strings.openMatches}</Link></div></div> : null}
    {available ? <VerifiedPlayback data={data} formatDateTime={formatDateTime} formatPercent={formatPercent} /> : null}
  </section>;
}

function VerifiedPlayback({ data, formatDateTime, formatPercent }: { data: Playback; formatDateTime: ReturnType<typeof useLocale>["formatDateTime"]; formatPercent: ReturnType<typeof useLocale>["formatPercent"] }) {
  const { locale, localizedHref, t, timeZone } = useLocale(); const strings = copy[locale];
  const { replay, verification, room } = data as Required<Pick<Playback, "replay" | "verification" | "room">> & Playback;
  const verified = verification.status === "verified" && replay.proof.hashChainValid && replay.proof.projectionMatches && replay.proof.rankingMatches && replay.proof.authorityValid && replay.proof.determinismValid;
  const result = `${stableOptionLabel(t, replay.resolution.winningOptionId)} · ${t("review.pointsApplied", { points: replay.scoring.totalPointsApplied })}`;
  const conclusions = deriveReviewConclusions(t, replay);
  const date = (value: string) => formatDateTime(value, { dateStyle: "medium", timeStyle: "medium", timeZone });
  return <div className="mt-10"><div className="grid gap-px bg-white/15 lg:grid-cols-[1.2fr_.8fr]"><div className="bg-[#070b15] p-6 sm:p-8 lg:p-10"><p className="font-['DM_Mono'] text-[9px] uppercase text-primary">{room.match.homeTeam.name} × {room.match.awayTeam.name}</p><h3 className="mt-5 font-['Chakra_Petch'] text-[clamp(2.2rem,5vw,4.8rem)] font-black uppercase leading-[.9]">{replayQuestion(t, replay, room)}</h3><p className="mt-5 max-w-2xl text-xs leading-5 text-white/40">{strings.capturedDisclosure}</p><h4 className="mt-10 border-t border-white/15 pt-7 font-['DM_Mono'] text-[10px] uppercase text-primary">{strings.chainTitle}</h4><ol className="mt-3"><EvidenceStep icon={Radio} title={strings.input} description={strings.inputDescription} values={[`${strings.market}: ${replay.technical.marketType ?? replay.prompt.marketSignature}`, `${strings.sequence}: ${replay.resolution.providerSequence ?? "—"}`, `${strings.observed}: ${date(replay.opening.observedAt)}`]} /><EvidenceStep icon={LockKeyhole} title={strings.lock} description={strings.lockDescription} values={[`${strings.answers}: ${replay.participation.confirmedAnswers}`, `${strings.lockedAt}: ${date(replay.lock.lockedAt)}`]} /><EvidenceStep icon={Clock3} title={strings.rule} description={strings.ruleDescription} values={[`${strings.expression}: ${replay.resolution.expression}`, replayResolutionLabel(t, replay, formatPercent)]} /><EvidenceStep icon={Trophy} title={strings.output} description={strings.outputDescription} values={[`${strings.winner}: ${stableOptionLabel(t, replay.resolution.winningOptionId)}`, `${strings.points}: ${replay.scoring.totalPointsApplied}`]} /></ol></div>
      <aside className="bg-[#0a101b] p-6 sm:p-8 lg:p-10"><ShieldCheck className="size-8 text-primary" /><p className="mt-5 font-['DM_Mono'] text-[9px] uppercase text-white/35">{strings.proofTitle}</p><h3 className="mt-2 font-['Chakra_Petch'] text-3xl font-black uppercase">{t(verified ? "playback.completed" : "playback.pending")}</h3><div className="mt-7 grid gap-px bg-white/10">{conclusions.map((item) => <article key={item.id} className="bg-[#0a101b] p-4"><p className="font-['DM_Mono'] text-[9px] uppercase text-white/35">{item.label}</p><p className="mt-2 text-xs leading-5 text-white/65">{item.copy}</p><span className={`mt-3 block h-1 w-8 ${item.valid ? "bg-primary" : "bg-amber-300"}`} /></article>)}</div><details className="mt-8 border border-white/10"><summary className="cursor-pointer p-4 font-['DM_Mono'] text-[9px] uppercase text-white/45">{strings.technical}</summary><div className="space-y-3 border-t border-white/10 p-4 font-['DM_Mono'] text-[9px] text-white/35"><Technical label={strings.fixtureType} value={data.source?.fixtureType ?? "sanitized_txline_test_fixture"} /><Technical label={strings.acquisition} value={replay.resolution.acquisitionOrigin} /><Technical label={strings.round} value={replay.roundId} /><Technical label={strings.replayHash} value={replay.replayHash} /><Technical label={strings.eventRange} value={replay.proof.roundEventRangeHash} /><Technical label={strings.stream} value={`${replay.proof.firstStreamVersion} → ${replay.proof.lastStreamVersion}`} /></div></details><Link to={localizedHref(`/match/${room.roomId}`)} className="mt-6 flex min-h-14 items-center justify-between bg-primary px-5 text-xs font-black uppercase text-[#050814]">{strings.openMatch}<ArrowRight className="size-4" /></Link><p className="mt-4 font-['DM_Mono'] text-[9px] uppercase text-white/25">{result}</p></aside></div></div>;
}

function PathCard({ eyebrow, title, description, steps, cta, href, icon: Icon }: { eyebrow: string; title: string; description: string; steps: readonly string[]; cta: string; href: string; icon: Icon }) { return <article className="flex min-h-[430px] flex-col bg-[#070b15] p-6 sm:p-8"><Icon className="size-6 text-primary" /><p className="mt-8 font-['DM_Mono'] text-[9px] uppercase text-primary">{eyebrow}</p><h3 className="mt-3 font-['Chakra_Petch'] text-4xl font-black uppercase">{title}</h3><p className="mt-4 text-sm leading-6 text-white/50">{description}</p><ul className="mt-7 space-y-3 border-t border-white/10 pt-5">{steps.map((step) => <li key={step} className="flex gap-3 text-xs text-white/60"><Check className="mt-0.5 size-3 shrink-0 text-primary" />{step}</li>)}</ul><a href={href} className="mt-auto flex min-h-12 items-center justify-between border border-white/15 px-4 text-[10px] font-black uppercase hover:border-primary hover:text-primary">{cta}<ArrowRight className="size-4" /></a></article>; }
function EvidenceStep({ icon: Icon, title, description, values }: { icon: Icon; title: string; description: string; values: string[] }) { return <li className="grid gap-4 border-b border-white/15 py-6 sm:grid-cols-[44px_1fr]"><span className="grid size-11 place-items-center border border-primary/30 text-primary"><Icon className="size-4" /></span><div><h5 className="font-['Chakra_Petch'] text-xl font-black uppercase">{title}</h5><p className="mt-2 text-xs leading-5 text-white/45">{description}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2">{values.map((value) => <span key={value} className="break-all font-['DM_Mono'] text-[9px] uppercase text-white/35">{value}</span>)}</div></div></li>; }
function Technical({ label, value }: { label: string; value: string }) { return <p><span className="text-primary">{label}</span><br /><span className="break-all">{value}</span></p>; }
function ExternalTextLink({ href, label }: { href: string; label: string }) { return <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-['DM_Mono'] text-[9px] uppercase text-white/55 hover:text-primary">{label}<ExternalLink className="size-3" /></a>; }
function ExternalButton({ href, label, icon: Icon }: { href: string; label: string; icon: Icon }) { return <a href={href} target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-between border border-white/15 bg-[#070b15] px-5 text-xs font-black uppercase hover:border-primary hover:text-primary"><span className="flex items-center gap-3"><Icon className="size-4" />{label}</span><ExternalLink className="size-4" /></a>; }
