import { ArrowRight, Check, Clock3, Radio, RefreshCw, ShieldCheck, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router";
import { useShellAtmosphere } from "../../app/shell/use-shell-atmosphere";
import { fetchPublicPlayback } from "../../runtime/api";
import { ViraLoader } from "../../shared/brand/ViraLoader";

type Playback = Awaited<ReturnType<typeof fetchPublicPlayback>>;
export function HelpScreen() {
  const [data, setData] = useState<Playback | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useShellAtmosphere("route:help", { atmosphere: "finished", context: "post-match", fixtureFocus: .18, priority: 20 });
  const load = () => { setState("loading"); void fetchPublicPlayback().then((value) => { setData(value); setState("ready"); }).catch(() => setState("error")); };
  useEffect(load, []);
  if (state === "loading") return <main className="grid min-h-[calc(100dvh-72px)] place-items-center"><ViraLoader label="Reconstruindo experiência verificada" /></main>;
  if (state === "error" || !data?.available || !data.replay || !data.verification || !data.room) return <Empty onRetry={load} />;
  const { replay, verification, room } = data;
  const verified = verification.status === "verified" && replay.proof.hashChainValid && replay.proof.projectionMatches && replay.proof.rankingMatches;
  return <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 lg:px-12 lg:py-16"><header className="border-b border-white/15 pb-8"><p className="font-['DM_Mono'] text-[10px] font-black uppercase tracking-[.16em] text-primary">Judge Playback · sem login</p><h1 className="mt-4 font-['Chakra_Petch'] text-[clamp(3rem,8vw,7.5rem)] font-black uppercase leading-[.8]">Experiência<br />verificada</h1><p className="mt-6 max-w-2xl text-sm leading-6 text-white/50">Uma rodada real preservada no ledger e reconstruída pelo mesmo runtime da sala. Nenhuma animação separada e nenhuma mutação administrativa.</p></header><section className="grid gap-px bg-white/15 lg:grid-cols-[1.2fr_.8fr]"><div className="bg-[#070b15] p-6 sm:p-8"><p className="font-['DM_Mono'] text-[9px] uppercase text-primary">{room.match.homeTeam.name} × {room.match.awayTeam.name}</p><h2 className="mt-4 font-['Chakra_Petch'] text-[clamp(2rem,5vw,4.5rem)] font-black uppercase leading-[.9]">{replay.prompt.text}</h2><ol className="mt-8 border-t border-white/15"><Step icon={Clock3} label="Rodada aberta" value={`${replay.participation.confirmedAnswers} respostas confirmadas`} /><Step icon={Radio} label="Fato TxLINE" value={replay.resolution.expression} /><Step icon={Trophy} label="Resultado" value={`${replay.resolution.winningOptionId.toUpperCase()} venceu · ${replay.scoring.totalPointsApplied} pontos`} /></ol></div><aside className="bg-[#0a101b] p-6 sm:p-8"><ShieldCheck className="size-7 text-primary" /><p className="mt-5 font-['DM_Mono'] text-[9px] uppercase text-white/35">Resultado verificado</p><h2 className="mt-2 font-['Chakra_Petch'] text-3xl font-black uppercase">{verified ? "Reprodução concluída" : "Verificação pendente"}</h2><ul className="mt-7 space-y-3 text-xs font-black uppercase"><Proof valid={replay.proof.hashChainValid} label="A partida foi reproduzida" /><Proof valid={replay.proof.projectionMatches} label="O resultado foi o mesmo" /><Proof valid={replay.proof.rankingMatches} label="A classificação foi a mesma" /></ul><details className="mt-8 border border-white/10"><summary className="cursor-pointer p-4 font-['DM_Mono'] text-[9px] uppercase text-white/45">Detalhes técnicos</summary><div className="border-t border-white/10 p-4 font-['DM_Mono'] text-[9px] text-white/35"><p>ROOM {room.roomId}</p><p className="mt-2 break-all">REPLAY {replay.replayHash}</p><p className="mt-2">STREAM {replay.proof.firstStreamVersion} → {replay.proof.lastStreamVersion}</p></div></details><Link to={`/match/${room.roomId}`} className="mt-6 flex min-h-14 items-center justify-between bg-primary px-5 font-black uppercase text-[#050814]">Abrir partida <ArrowRight className="size-4" /></Link></aside></section></main>;
}
function Step({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <li className="grid grid-cols-[40px_1fr] gap-4 border-b border-white/15 py-5"><span className="grid size-10 place-items-center border border-primary/30 text-primary"><Icon className="size-4" /></span><div><p className="font-['DM_Mono'] text-[9px] uppercase text-primary">{label}</p><p className="mt-1 text-sm font-black uppercase">{value}</p></div></li>; }
function Proof({ valid, label }: { valid: boolean; label: string }) { return <li className="flex items-center gap-3"><span className={`grid size-6 place-items-center border ${valid ? "border-primary text-primary" : "border-amber-300 text-amber-300"}`}><Check className="size-3" /></span>{label}</li>; }
function Empty({ onRetry }: { onRetry: () => void }) { return <main className="grid min-h-[calc(100dvh-72px)] place-items-center px-5 text-center"><div><p className="font-['DM_Mono'] text-[10px] uppercase text-primary">Judge Playback</p><h1 className="mt-4 font-['Chakra_Petch'] text-4xl font-black uppercase">Playback temporariamente indisponível</h1><p className="mx-auto mt-4 max-w-xl text-sm text-white/45">O playback aparece quando uma rodada resolvida e reproduzível existe no ledger público.</p><div className="mt-7 flex justify-center gap-2"><button type="button" onClick={onRetry} className="inline-flex min-h-12 items-center gap-2 border border-white/20 px-5 text-xs font-black uppercase"><RefreshCw className="size-4" /> Tentar novamente</button><Link to="/matches" className="inline-flex min-h-12 items-center bg-primary px-5 text-xs font-black uppercase text-[#050814]">Abrir partidas</Link></div></div></main>; }
